# Generated by Django 4.1.7 on 2023-02-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='Slider name1')),
                ('name2', models.CharField(max_length=30, verbose_name='Slider name2')),
                ('text', models.TextField(verbose_name='Slider text')),
                ('button_name', models.CharField(max_length=20, verbose_name='Slider button name')),
                ('img1', models.ImageField(upload_to='media', verbose_name='Slider image1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Slider image2')),
            ],
            options={
                'verbose_name': 'HomeSliders',
            },
        ),
        migrations.CreateModel(
            name='HomeSliderActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30, verbose_name='SliderActive name1')),
                ('name2', models.CharField(max_length=30, verbose_name='SliderActive name2')),
                ('text', models.TextField(verbose_name='SliderActive text')),
                ('button_name', models.CharField(max_length=20, verbose_name='SliderActive button name')),
                ('img1', models.ImageField(upload_to='media', verbose_name='SliderActive image1')),
                ('img2', models.ImageField(upload_to='media', verbose_name='SliderActive image2')),
            ],
            options={
                'verbose_name': 'HomeSlidersActive',
            },
        ),
    ]
