# Generated by Django 4.1.7 on 2023-02-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_homeslider_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Product image')),
                ('price', models.IntegerField(verbose_name='Product price')),
                ('addition', models.ImageField(blank=True, upload_to='media', verbose_name='Product addition')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
